baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'working'
enableGitInfo = true

[params]
  authorName = "Shaurya singh"
  tagline = "Finding my place between beauty and practicality"
  subtitle = "Software Designer | Creative Technologist"
  currentRole = "Lead UX at [Wongdoody](https://www.wongdoody.com/)"
  description = "Portfolio of Shaurya - Software Designer & Creative Technologist"

[params.social]
  twitter = "yourusername"
  github = "yourusername"
  linkedin = "yourusername"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true